FROM eclipse-temurin:17.0.5_8-jre-focal

LABEL Description="Eureka Server" Version="0.0.1"

ARG VERSION=0.0.1

VOLUME /tmp

ADD target/eureka-server-0.0.1-SNAPSHOT.jar eureka-server.jar

ENTRYPOINT ["java", "-jar", "eureka-server.jar"]